[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="calc_lib"
path="src/lib.rs"

[[bin]]
name="calc_repl"
path="src/main.rs"
